---
- name: Configure system
  hosts: mini
  vars_files:
    - vars/public.yml
    - vars/vault.yml
  roles:
    - role: journal
    - role: credentials
    - role: terminal
    - role: automation
    - role: version_control
